version: '3.9'

services:
  # Application
  app:
    build:
      context: .
      dockerfile: _docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "database"
    networks:
      - web
      - internal
    container_name: hk_app
  # Web Server
  server:
    build:
      context: .
      dockerfile: _docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "app"
    container_name: hk_server
    labels:
      - "traefik.http.routers.server.rule=Host(`api.djtresk.ru`)"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
    networks:
      - web
      - internal
  # Database
  database:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      environment:
      MYSQL_DATABASE: hk
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "33061:3306"
    container_name: hk_db
    networks:
      - internal
      - web
  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - "8888:80"
    networks:
      - web
      - internal
    container_name: hk_pma

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  dbdata:
